#!/bin/bash
VER=11.x
clear

if [ ! `whoami` = "root" ] 
then 
    echo "The installer should be run as root"
    exit 0
fi

glroot="/glftpd"

if [ -d "$glroot" ]
then
    echo -n "The path you have chosen already exists, what would you like to do [D]elete it, [A]bort, [T]ry again, [I]gnore? " ; read reply
    case $reply in
	[dD]*) rm -rf "$glroot" ;;
	[tT]*) glroot="./"; continue ;;
	[iI]*) ;;
	*) echo "Aborting."; exit 1 ;;
    esac
fi

mkdir -p "$glroot"
if [ ! -d ".tmp" ]
then
    mkdir .tmp
fi
clear

echo "Welcome to the glFTPd installer v$VER"
echo
echo "Disclaimer:" 
echo "This software is used at your own risk!"
echo "The author of this installer takes no responsibility for any damage done to your system."
echo
echo -n "Have you read and installed the Requirements in README.MD ? [Y]es [N]o, default N : " ; read requirement
echo
case $requirement in
    [Yy]) ;;
    [Nn]) rm -r /glftpd && rm -r .tmp ; exit 1 ;;
    *) rm -r /glftpd && rm -r .tmp ; exit 1 ;;
esac

if [ "`echo $PATH | grep /usr/sbin | wc -l`" = 0 ]
then 
    echo "/usr/sbin not found in environmental PATH" 
    echo "Default PATH should be : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    echo "Current PATH is : `echo $PATH`"
    echo "Correcting PATH"
    export PATH=$PATH:/usr/sbin
    echo "Done"
    echo
fi

rootdir=`pwd`
cache="$rootdir/install.cache"

# Clean up comments and trailing spaces in install.cache to avoid problems with unattended installation
if [ -f "$cache" ]
then
    sed -i -e 's/" #.*/"/g' -e 's/^#.*//g' -e '/^\s*$/d' -e 's/[ \t]*$//' $cache
fi

# Global variables for section management
pzsbot="$glroot/sitebot/scripts/pzs-ng/ngBot.conf"
pzsng="$glroot/backup/pzs-ng"
incoming="/glftpd/site" 

# Optional configuration files
turautonuke="$glroot/bin/tur-autonuke.conf"
turspace="$glroot/bin/tur-space.conf"
approve="$glroot/bin/approve.sh"
foopre="$glroot/etc/pre.cfg"
turlastul="$glroot/bin/tur-lastul.sh"
psxcimdb="$glroot/etc/psxc-imdb.conf"
dated="$glroot/bin/dated.sh"

# Variables for section workflow
declare -A section_details
deferred_operations_file="$rootdir/.tmp/deferred_sections.sh"


#=============================================================================
# SECTION MANAGEMENT FUNCTIONS
#=============================================================================

## Validate prerequisites for section creation
function validate_prerequisites() {
    local validation_passed=true
    
    #printf "Validating section management prerequisites...\n"
    
    # Check compilation tools
    if ! command -v make >/dev/null 2>&1; then
        printf "WARNING: 'make' tool not available - pzs-ng recompilation deferred\n"
        validation_passed=false
    fi
    
    if ! command -v gcc >/dev/null 2>&1; then
        printf "WARNING: 'gcc' compiler not available - pzs-ng recompilation deferred\n"
        validation_passed=false
    fi
    
    # Check pzs-ng sources (may not be available during installation)
    if [[ ! -d "$pzsng" ]]; then
        validation_passed=false
    elif [[ ! -f "$pzsng/zipscript/conf/zsconfig.h" ]]; then
        validation_passed=false
    fi
    
    # Create deferred operations file if needed
    if [[ "$validation_passed" = false ]]; then
        initialize_deferred_operations
    fi
    
    return 0  # Always continue, even with deferred operations
}

## Initialize deferred operations system
function initialize_deferred_operations() {
    if [[ ! -f "$deferred_operations_file" ]]; then
        cat > "$deferred_operations_file" << 'EOF'
#!/bin/bash
# Deferred section finalization script
# Automatically generated by install.sh
# Execute after complete glFTPd installation

glroot="/glftpd"
pzsng="$glroot/backup/pzs-ng"
pzsbot="$glroot/sitebot/scripts/pzs-ng/ngBot.conf"

printf "Finalizing deferred section operations...\n"

EOF
        chmod +x "$deferred_operations_file"
        #printf "Deferred operations file created: %s\n" "$deferred_operations_file"
    fi
}

## Enhanced section details collection
function prompt_section_details() {
    local section_index=$1
    local section_name=""
    local section_dated=""
    local section_zipfiles=""
    local section_movie=""
    
    # Check cache for basic information
    if [[ -f "$cache" && "`grep -w "section${section_index}" $cache | wc -l`" = 1 ]]; then
        section_name=`grep -w "section${section_index}" $cache | cut -d "=" -f2 | tr -d "\""`
    else
        if [ "$section_index" = "1" ]; then
            printf "Recommended sections:\n"
            printf "0DAY ANIME APPS DOX EBOOKS FLAC GAMES MBLURAY MP3 NSW PS4 PS5 TV-1080 TV-2160\n"
            printf "TV-720 TV-HD TV-NL X264 X264-1080 X264-720 X265-2160 XVID XXX XXX-PAYSITE\n"
            printf "\n"
        fi
        
        while [[ -z "$section_name" ]]; do
            printf "Section %s is: " "$section_index" ; read section_name
        done
        
        # Save to cache
        if [[ -f "$cache" && "`grep -w "section${section_index}=" $cache | wc -l`" = 0 ]]; then
            printf "section%s=\"%s\"\n" "$section_index" "$section_name" >> $cache
        fi
    fi
    
    # Check cache for dated type
    if [[ -f "$cache" && "`grep -w "section${section_index}dated" $cache | wc -l`" = 1 ]]; then
        section_dated=`grep -w "section${section_index}dated" $cache | cut -d "=" -f2 | tr -d "\""`
    else
        printf "Is section %s a dated section? [Y]es [N]o, default N: " "${section_name^^}" ; read section_dated
        if [[ -f "$cache" && "`grep -w "section${section_index}dated=" $cache | wc -l`" = 0 ]]; then
            if [[ "$section_dated" = "y" || "$section_dated" = "Y" ]]; then
                printf "section%sdated=\"y\"\n" "$section_index" >> $cache
            else
                printf "section%sdated=\"n\"\n" "$section_index" >> $cache
                section_dated="n"
            fi
        fi
    fi
    
    # Questions
    if [[ -f "$cache" && "`grep -w "section${section_index}zipfiles" $cache | wc -l`" = 1 ]]; then
        section_zipfiles=`grep -w "section${section_index}zipfiles" $cache | cut -d "=" -f2 | tr -d "\""`
    else
        printf "Does this section contain ZIP files? [Y]es [N]o, default N: " ; read section_zipfiles
        if [[ -f "$cache" && "`grep -w "section${section_index}zipfiles=" $cache | wc -l`" = 0 ]]; then
            if [[ "$section_zipfiles" = "y" || "$section_zipfiles" = "Y" ]]; then
                printf "section%szipfiles=\"y\"\n" "$section_index" >> $cache
            else
                printf "section%szipfiles=\"n\"\n" "$section_index" >> $cache
                section_zipfiles="n"
            fi
        fi
    fi
    
    # Movie section question
    if [[ -f "$cache" && "`grep -w "section${section_index}movie" $cache | wc -l`" = 1 ]]; then
        section_movie=`grep -w "section${section_index}movie" $cache | cut -d "=" -f2 | tr -d "\""`
    else
        printf "Is this a movie section? [Y]es [N]o, default N: " ; read section_movie
        if [[ -f "$cache" && "`grep -w "section${section_index}movie=" $cache | wc -l`" = 0 ]]; then
            if [[ "$section_movie" = "y" || "$section_movie" = "Y" ]]; then
                printf "section%smovie=\"y\"\n" "$section_index" >> $cache
            else
                printf "section%smovie=\"n\"\n" "$section_index" >> $cache
                section_movie="n"
            fi
        fi
    fi
    
    # Store details in global associative array
    section_details["${section_index}_name"]="${section_name^^}"
    section_details["${section_index}_dated"]="$section_dated"
    section_details["${section_index}_zipfiles"]="$section_zipfiles"
    section_details["${section_index}_movie"]="$section_movie"
    
    #printf "Section %s configured successfully\n" "${section_name^^}"
}

## Create section directory with appropriate permissions
function create_section_directory() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_path="$glroot/site/$section_name"
    
    #printf "Creating directory for section %s...\n" "$section_name"
    
    # Create main directory
    mkdir -pm 777 "$rootdir/.tmp/site/$section_name"
    
    # Create final directory if glroot exists
    if [[ -d "$glroot" ]]; then
        mkdir -pm 777 "$section_path"
        #printf "Directory created: %s\n" "$section_path"
    else
        printf "glroot directory not yet available - creation deferred\n"
    fi
    
    return 0
}

## Update zsconfig.h and recompile pzs-ng
function update_zsconfig_and_recompile() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_dated="${section_details["${section_index}_dated"]}"
    local section_zipfiles="${section_details["${section_index}_zipfiles"]}"
    local zsconfig_path="$pzsng/zipscript/conf/zsconfig.h"
    
    # Check pzs-ng availability
    if [[ ! -f "$zsconfig_path" ]]; then
        #printf "zsconfig.h not available - adding to deferred operations list\n"
        add_to_deferred_operations "update_zsconfig_and_recompile" "$section_name" "$section_dated" "$section_zipfiles"
        return 0
    fi
    
    #printf "Updating zsconfig.h for section %s...\n" "$section_name"
    
    # Safety backup
    cp "$zsconfig_path" "$zsconfig_path.backup.$(date +%s)"
    
    # Modifications based on section type
    if [[ "$section_dated" = "y" ]]; then
        sed -i "/\bcleanupdirs_dated\b/ s/\"$/ \/site\/$section_name\/%Y-%m-%d\/\"/" "$zsconfig_path"
    else
        sed -i "/\bcleanupdirs\b/ s/\"$/ \/site\/$section_name\/\"/" "$zsconfig_path"
    fi
    
    # Configuration based on file type
    if [[ "$section_zipfiles" = "y" ]]; then
        sed -i "/\bzip_dirs\b/ s/\"$/ \/site\/$section_name\/\"/" "$zsconfig_path"
    else
        sed -i "/\bsfv_dirs\b/ s/\"$/ \/site\/$section_name\/\"/" "$zsconfig_path"
    fi
    
    # Add for missing NFO check
    sed -i "/\bcheck_for_missing_nfo_dirs\b/ s/\"$/ \/site\/$section_name\/\"/" "$zsconfig_path"
    
    # Recompile if tools are available
    if command -v make >/dev/null 2>&1; then
        perform_pzsng_recompilation
    else
        printf "Compilation tools not available - recompilation deferred\n"
        add_to_deferred_operations "perform_pzsng_recompilation"
    fi
    
    return 0
}

## Robust pzs-ng recompilation cycle
function perform_pzsng_recompilation() {
    local current_dir=$(pwd)
    
    printf "Recompiling pzs-ng..."
    
    cd "$pzsng" || {
        printf "ERROR: Cannot access pzs-ng directory\n"
        return 1
    }
    
    # Complete recompilation cycle
    make distclean >/dev/null 2>&1
    ./configure -q >/dev/null 2>&1 || {
        printf "ERROR: Configuration failed\n"
        cd "$current_dir"
        return 1
    }
    
    make >/dev/null 2>&1 || {
        printf "ERROR: Compilation failed\n"
        cd "$current_dir"
        return 1
    }
    
    make install >/dev/null 2>&1 || {
        printf "ERROR: Installation failed\n"
        cd "$current_dir"
        return 1
    }
    
    cd "$current_dir"
    printf "   \033[32mDone\033[0m\n"
    return 0
}

## Update IRC bot configuration
function update_ngbot_configuration() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_dated="${section_details["${section_index}_dated"]}"
    
    # Check configuration file availability
    if [[ ! -f "$pzsbot" ]]; then
        #printf "ngBot.conf not available - configuration deferred\n"
        add_to_deferred_operations "update_ngbot_configuration" "$section_name" "$section_dated"
        
        # Create temporary bot config files
        create_temporary_bot_config "$section_index"
        return 0
    fi
    
    printf "Updating bot configuration for section %s...\n" "$section_name"
    
    # Add section to global list
    sed -i "/set sections/s/\"$/\ $section_name\"/g" "$pzsbot"
    
    # Configure paths based on type
    if [[ "$section_dated" = "y" ]]; then
        sed -i '/set paths(REQUEST)/i set paths('"$section_name"')				"/site/'"$section_name"'/*/*"' "$pzsbot"
        sed -i '/set chanlist(REQUEST)/i set chanlist('"$section_name"')                 "$spamchan"' "$pzsbot"
    else
        sed -i '/set paths(REQUEST)/i set paths('"$section_name"')				"/site/'"$section_name"'/*"' "$pzsbot"
        sed -i '/set chanlist(REQUEST)/i set chanlist('"$section_name"')                 "$mainchan"' "$pzsbot"
    fi
    
    # Clean up configuration
    sed -i '/set sections/s/  / /g' "$pzsbot"
    sed -i '/set sections/s/ "/"/g' "$pzsbot"
    sed -i '/set sections/s/" /"/g' "$pzsbot"
    
    printf "Bot configuration updated for %s\n" "$section_name"
    return 0
}

## Create temporary bot config files
function create_temporary_bot_config() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_dated="${section_details["${section_index}_dated"]}"
    
    printf "%s " "$section_name" > "$rootdir/.tmp/.section" && cat "$rootdir/.tmp/.section" >> "$rootdir/.tmp/.sections"
    cat "$rootdir/.tmp/.sections" | awk -F '[" "]+' '{printf $0}' > "$rootdir/.tmp/.validsections"
    
    if [[ "$section_dated" = "y" ]]; then
        printf "set paths(%s)				\"/site/%s/*/*\"\n" "$section_name" "$section_name" >> "$rootdir/.tmp/dzsrace"
        printf "set chanlist(%s) 			\"$channelspam\"\n" "$section_name" >> "$rootdir/.tmp/dzschan"
    else
        printf "set paths(%s) 			\"/site/%s/*\"\n" "$section_name" "$section_name" >> "$rootdir/.tmp/dzsrace"
        printf "set chanlist(%s) 			\"$channelmain\"\n" "$section_name" >> "$rootdir/.tmp/dzschan"
    fi
}

## Update auxiliary scripts
function update_auxiliary_scripts() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_dated="${section_details["${section_index}_dated"]}"
    local section_movie="${section_details["${section_index}_movie"]}"
    
    #printf "Updating auxiliary scripts for %s...\n" "$section_name"
    
    # Update tur-autonuke
    update_tur_autonuke_config "$section_name" "$section_dated"
    
    # Update tur-space
    update_tur_space_config "$section_name"
    
    # Update foo-pre
    update_foo_pre_config "$section_name" "$section_dated"
    
    # Conditional update of other scripts
    if [[ -f "$approve" ]]; then
        update_approve_script "$section_name"
    fi
    
    if [[ -f "$turlastul" ]]; then
        update_tur_lastul_script "$section_name"
    fi
    
    if [[ "$section_movie" = "y" && -f "$psxcimdb" ]]; then
        update_psxc_imdb_config "$section_name"
    fi
    
    if [[ "$section_dated" = "y" && -f "$dated" ]]; then
        update_dated_script "$section_name"
    fi
    
    return 0
}

## Update tur-autonuke
function update_tur_autonuke_config() {
    local section_name=$1
    local section_dated=$2
    
    # Modify configuration file
    if [[ "$section_dated" = "y" ]]; then
        sed -i "s/\bDIRS=\"/DIRS=\"\n\/site\/$section_name\/\$today/" packages/modules/tur-autonuke/tur-autonuke.conf
        sed -i "s/\bDIRS=\"/DIRS=\"\n\/site\/$section_name\/\$yesterday/" packages/modules/tur-autonuke/tur-autonuke.conf
    else
        sed -i "s/\bDIRS=\"/DIRS=\"\n\/site\/$section_name/" packages/modules/tur-autonuke/tur-autonuke.conf
    fi
    
    # If final file exists, update directly
    if [[ -f "$turautonuke" ]]; then
        if [[ "$section_dated" = "y" ]]; then
            sed -i '/^DIRS/a '"/site/$section_name/\$today" "$turautonuke"
            sed -i '/^DIRS/a '"/site/$section_name/\$yesterday" "$turautonuke"
        else
            sed -i '/^DIRS/a '"/site/$section_name" "$turautonuke"
        fi
    fi
}

## Update tur-space
function update_tur_space_config() {
    local section_name=$1
    
    printf "INC%s=%s:%s/site/%s:\n" "$section_name" "$device" "$glroot" "$section_name" >> packages/scripts/tur-space/tur-space.conf.new
    
    if [[ -f "$turspace" ]]; then
        sed -i '/^\[INCOMING\]/a '"INC$section_name=$incoming:$glroot/site/$section_name:" "$turspace"
    fi
}

## Update foo-pre
function update_foo_pre_config() {
    local section_name=$1
    local section_dated=$2
    
    # Create temporary files
    printf "section.%s.name=%s\n" "$section_name" "$section_name" >> "$rootdir/.tmp/footools"
    if [[ "$section_dated" = "y" ]]; then
        printf "section.%s.dir=/site/%s/%%YYYY-%%MM-%%DD\n" "$section_name" "$section_name" >> "$rootdir/.tmp/footools"
    else
        printf "section.%s.dir=/site/%s\n" "$section_name" "$section_name" >> "$rootdir/.tmp/footools"
    fi
    printf "section.%s.gl_credit_section=0\n" "$section_name" >> "$rootdir/.tmp/footools"
    printf "section.%s.gl_stat_section=0\n" "$section_name" >> "$rootdir/.tmp/footools"
    
    # Direct update if final file exists
    if [[ -f "$foopre" ]]; then
        sed -i "s/.allow=/.allow=$section_name\|/" "$foopre"
        if [[ "$section_dated" = "y" ]]; then
            printf "section.%s.name=%s\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.dir=/site/%s/YYYY-MM-DD\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.gl_credit_section=0\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.gl_stat_section=0\n" "$section_name" "$section_name" >> "$foopre"
        else
            printf "section.%s.name=%s\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.dir=/site/%s\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.gl_credit_section=0\n" "$section_name" "$section_name" >> "$foopre"
            printf "section.%s.gl_stat_section=0\n" "$section_name" "$section_name" >> "$foopre"
        fi
        
        # Cleanup
        sed -i "/allow=/s/=|/=/" "$foopre"
        sed -i "/allow=/s/||/|/" "$foopre"
        sed -i "/allow=/s/|$//" "$foopre"
    fi
}

## Add operations to deferred tasks
function add_to_deferred_operations() {
    local operation=$1
    shift
    local args="$@"
    
    printf "# Deferred operation: %s\n" "$operation" >> "$deferred_operations_file"
    printf "%s %s\n" "$operation" "$args" >> "$deferred_operations_file"
    printf "\n" >> "$deferred_operations_file"
}

## Handle specialized sections
function handle_specialized_sections() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    local section_movie="${section_details["${section_index}_movie"]}"
    
    # Special handling for movie sections
    #if [[ "$section_movie" = "y" ]]; then
    #    printf "Special configuration for movie section %s\n" "$section_name"
        # PSXC-IMDB configuration will be handled in update_auxiliary_scripts
    #fi
    
    # Handling of special sections (0DAY, MP3, FLAC, EBOOKS)
    #case "${section_name^^}" in
    #    "0DAY"|"MP3"|"FLAC"|"EBOOKS")
    #        printf "Special section detected: %s - adapted configuration\n" "$section_name"
             # These sections require special handling in approve.sh
    #        ;;
    #esac
    
    return 0
}

## Finalize section creation
function finalize_section_creation() {
    local section_index=$1
    local section_name="${section_details["${section_index}_name"]}"
    
    # Update tracking files
    printf "%s/site/%s\n" "$glroot" "$section_name" >> "$rootdir/.tmp/.fullpath"
    
    if [[ "${section_details["${section_index}_dated"]}" = "y" ]]; then
        printf "/site/%s/%%Y-%%m-%%d/ \n" "$section_name" >> "$rootdir/.tmp/.cleanup_dated"
        
        # Special handling for 0DAY
        if [[ "$section_name" != "0DAY" ]]; then
            printf "/site/%s/ \n" "$section_name" > "$rootdir/.tmp/.section" && cat "$rootdir/.tmp/.section" >> "$rootdir/.tmp/.tempdated"
            cat "$rootdir/.tmp/.tempdated" | awk -F '[" "]+' '{printf $0}' > "$rootdir/.tmp/.path"
        fi
    else
        printf "/site/%s/ \n" "$section_name" > "$rootdir/.tmp/.section" && cat "$rootdir/.tmp/.section" >> "$rootdir/.tmp/.temp"
        cat "$rootdir/.tmp/.temp" | awk -F '[" "]+' '{printf $0}' > "$rootdir/.tmp/.nodatepath"
    fi
    
    #printf "Section %s finalized successfully\n" "$section_name"
    return 0
}

## Main section creation workflow function
function create_section_workflow() {
    
    # Validate prerequisites
    validate_prerequisites
    
    # Collect number of sections
    if [[ -f "$cache" && "`grep -w "sections" $cache | wc -l`" = 1 ]]; then
        sections=`grep -w "sections" $cache | cut -d "=" -f2 | tr -d "\""`
    else
        printf "\n"
        while [[ ! $sections =~ ^[0-9]+$ ]]; do
            printf "How many sections do you need for your site? : " ; read sections
        done
        printf "\n"
    fi
    
    # Initialize configuration files
    cp packages/scripts/tur-rules/tur-rules.sh.org packages/scripts/tur-rules/tur-rules.sh
    packages/scripts/tur-rules/rulesgen.sh GENERAL
    cp packages/modules/tur-autonuke/tur-autonuke.conf.org packages/modules/tur-autonuke/tur-autonuke.conf
    cp packages/core/dated.sh.org "$rootdir/.tmp/dated.sh"
    
    # Counting variables
    local section_counter=0
    local rule_counter=2
    
    # Save number of sections in cache
    if [[ -f "$cache" && "`grep -w "sections=" $cache | wc -l`" = 0 ]]; then
        printf "sections=\"%s\"\n" "$sections" >> $cache
    fi
    
    # Main section creation loop
    while [ $section_counter -lt $sections ]; do
        local current_section=$((section_counter + 1))
        
        #printf "\n"
        #printf "=== Configuring section %s/%s ===\n" "$current_section" "$sections"
        
        # 1. Collect section details
        prompt_section_details "$current_section"
        
        # 2. Create directory
        create_section_directory "$current_section"
        
        # 3. Update zsconfig.h and recompile
        update_zsconfig_and_recompile "$current_section"
        
        # 4. Configure IRC bot
        update_ngbot_configuration "$current_section"
        
        # 5. Update auxiliary scripts
        update_auxiliary_scripts "$current_section"
        
        # 6. Handle specialized sections
        handle_specialized_sections "$current_section"
        
        # 7. Finalization
        finalize_section_creation "$current_section"
        
        # 8. Update site rules
        update_site_rules "$current_section" "$rule_counter"
        
        # Increment counters
        section_counter=$((section_counter + 1))
        rule_counter=$((rule_counter + 1))
        
        #printf "Section %s created successfully\n" "${section_details["${current_section}_name"]}"
        #printf "\n"
    done
    
    #printf "All sections have been configured successfully\n"
    
    #if [[ -f "$deferred_operations_file" ]]; then
    #    printf "\n"
    #    printf "IMPORTANT: Some operations have been deferred.\n"
    #    printf "Execute the following script after complete installation:\n"
    #    printf "%s\n" "$deferred_operations_file"
    #fi
}

## Update site rules
function update_site_rules() {
    local section_index=$1
    local rule_counter=$2
    local section_name="${section_details["${section_index}_name"]}"
    
    printf "%s :\n" "$section_name" >> site.rules
    if [ "$rule_counter" -ge 10 ]; then
        printf "%s.1 Main language: English/Nordic................................................................................[NUKE 5X]\n" "$rule_counter" >> site.rules
        printf "\n" >> site.rules
        sed -i "s/sections=\"/sections=\"\n$section_name:^$rule_counter./" packages/scripts/tur-rules/tur-rules.sh
    else
        printf "0%s.1 Main language: English/Nordic................................................................................[NUKE 5X]\n" "$rule_counter" >> site.rules
        printf "\n" >> site.rules
        sed -i "s/sections=\"/sections=\"\n$section_name:^0$rule_counter./" packages/scripts/tur-rules/tur-rules.sh
    fi
}


## Update approve script
function update_approve_script() {
    local section_name=$1
    
    if [[ ${section_name^^} != @(0DAY|MP3|FLAC|EBOOK) ]]; then
        sed -i '/^SECTIONS="/a '"$section_name" "$approve"
    else
        sed -i '/^DAYSECTIONS="/a '"$section_name" "$approve"
    fi
    
    # Update counters
    local sections_count=`sed -n '/^SECTIONS="/,/"/p' "$approve" | grep -v DAYSECTIONS | grep -v NUMDAYFOLDERS | grep -v SECTIONS | grep -v "\"" | wc -l`
    local daysections_count=`sed -n '/^DAYSECTIONS="/,/"/p' "$approve" | grep -v DAYSECTIONS | grep -v NUMDAYFOLDERS | grep -v SECTIONS | grep -v "\"" | wc -l`
    
    sed -i -e "s/^NUMFOLDERS=\".*\"/NUMFOLDERS=\"$sections_count\"/" "$approve"
    sed -i -e "s/^NUMDAYFOLDERS=\".*\"/NUMDAYFOLDERS=\"$daysections_count\"/" "$approve"
}

## Update tur-lastu script
function update_tur_lastul_script() {
    local section_name=$1
    
    sed -i "s/^sections=\"/sections=\"$section_name /" "$turlastul"
    
    # Cleanup
    sed -i '/^sections=/s/  / /g' "$turlastul"
    sed -i '/^sections=/s/" /"/g' "$turlastul"
    sed -i '/^sections=/s/ "/"/g' "$turlastul"
}

## Update PSXC-IMDB for movie sections
function update_psxc_imdb_config() {
    local section_name=$1
    
    sed -i "s/^SCANDIRS=\"/SCANDIRS=\"\/site\/$section_name /" "$psxcimdb"
    
    # Cleanup
    sed -i '/^SCANDIRS=/s/  / /g' "$psxcimdb"
    sed -i '/^SCANDIRS=/s/" /"/g' "$psxcimdb"
    sed -i '/^SCANDIRS=/s/ "/"/g' "$psxcimdb"
}

## Update dated script for dated sections
function update_dated_script() {
    local section_name=$1
    
    sed -i '/^sections="/a '"$section_name" "$dated"
}

function start
{
    echo "--------[ Server configuration ]--------------------------------------"
    echo
    if [[ -f "$cache" && "`grep -w "sitename" $cache | wc -l`" = 1 ]]
    then
	sitename=`grep -w "sitename" $cache | cut -d "=" -f2 | tr -d "\""`
	return
    fi
	
    while [[ -z $sitename ]]
    do
	echo -n "Please enter the name of the site, without space : " ; read sitename
    done
	
    sitename="`echo $sitename | sed 's/ /_/g'`"
	
    if [ ! -f "$cache" ]
    then
	echo sitename=\"$sitename\" > $cache
    fi
}

function port
{
    if [[ -f "$cache" && "`grep -w "port" $cache | wc -l`" = 1 ]]
    then
	port=`grep -w "port" $cache | cut -d "=" -f2 | tr -d "\""`
    else
	echo -n "Please enter the port number for your site, default 2010 : " ; read port
	
	if [ "$port" = "" ] 
	then
	    port="2010"
	fi
		
	if [[ -f "$cache" && "`grep -w "port=" $cache | wc -l`" = 0 ]]
	then
	    echo port=\"$port\" >> $cache
	fi
    fi
}

function version
{
    echo -n "Downloading relevant packages, please wait..." | awk '{printf("%-64s",$0)}'
    if [[ `curl -s https://glftpd.io | grep "/files/glftpd" | grep -v BETA | grep -o "glftpd-LNX.*.tgz" | head -1` == glftpd* ]]
    then
	url="https://glftpd.io"
    else
	if [[ `curl -s https://mirror.glftpd.nl.eu.org | grep "/files/glftpd" | grep -v BETA | grep -o "glftpd-LNX.*.tgz" | head -1` == glftpd* ]]
	then
	    url="https://mirror.glftpd.nl.eu.org"
	else
	    echo
	    echo
	    echo -e "\e[0;91mNo available website for downloading glFTPd, aborting installation.\e[0m"
	    exit 1
	fi
    fi
    latest=`curl -s $url | grep "/files/glftpd" | grep -v BETA | grep -o "glftpd-LNX.*.tgz" | head -1`
    version=`lscpu | grep Architecture | awk '{print $2}'`
    case $version in
	i686)
	    version="32"
	    latest=`echo $latest | sed 's/x64/x86/'`
	    cd packages && wget -q $url/files/$latest && cd ..
	    ;;
	x86_64)
	    version="64"
	    cd packages && wget -q $url/files/$latest && cd ..
	    ;;
    esac
    PK1=`echo $latest`
    PK1DIR=`echo $latest | sed 's|.tgz||'`
    PK2DIR="pzs-ng"
    PK3DIR="eggdrop"
    UP="tar xf"
    BOTU="sitebot"
    CHKGR=`grep -w "glftpd" /etc/group | cut -d ":" -f1`
    CHKUS=`grep -w "sitebot" /etc/passwd | cut -d ":" -f1`
    SQLPASSWD=`tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20; echo`
	
    if [ "$CHKGR" != "glftpd" ] 
    then
        groupadd glftpd -g 199
    fi
	
    if [ "$CHKUS" != "sitebot" ] 
    then
	useradd -d $glroot/sitebot -m -g glftpd -s /bin/bash $BOTU
	chfn -f 0 -r 0 -w 0 -h 0 $BOTU
    fi 
    cd packages
    #echo -n "Extracting the Source files, please wait...                     "
    $UP $PK1 && rm $PK1
    git clone https://github.com/glftpd/pzs-ng >/dev/null 2>&1
    git clone https://github.com/eggheads/eggdrop >/dev/null 2>&1
    echo -e "[\e[32mDone\e[0m]"
    echo
    mkdir source
    cp -R scripts source
    cd ..
    
    cp -f $rootdir/packages/core/cleanup.sh $rootdir
}

function device_name
{
    if [[ -f "$cache" && "`grep -w "device" $cache | wc -l`" = 1 ]]
    then
    	device=`grep -w "device" $cache | cut -d "=" -f2 | tr -d "\""`
    	echo "Sitename           = $sitename"
    	echo "Port               = $port"
    	echo "glFTPd version     = $version bit" 
    	echo "Device             = $device"
    else
    	echo "Please enter which device you will use for the $glroot/site folder"
    	echo "eg /dev/sda1"
    	echo "eg /dev/mapper/lvm-lvm"
    	echo "eg /dev/md0"
    	echo "Default: /dev/sda1"
    	echo -n "Device : " ; read device
    	echo
    
    	if [ "$device" = "" ] 
    	then
	    device="/dev/sda1"
	fi
	
    fi
    cp packages/scripts/tur-space/tur-space.conf packages/scripts/tur-space/tur-space.conf.new
    echo "[TRIGGER]" >> packages/scripts/tur-space/tur-space.conf.new
    echo "TRIGGER=$device:100000:200000" >> packages/scripts/tur-space/tur-space.conf.new
    echo "" >> packages/scripts/tur-space/tur-space.conf.new
    echo "[INCOMING]" >> packages/scripts/tur-space/tur-space.conf.new
    
    if [[ -f "$cache" && "`grep -w "device=" $cache | wc -l`" = 0 ]]
    then
    	echo device=\"$device\" >> $cache
    fi
}

function channel
{
    if [[ -f "$cache" && "`grep -w "ircserver" $cache | wc -l`" = 1 ]]
    then
        ircserver=`grep -w ircserver $cache | cut -d "=" -f2 | tr -d "\""`
        echo -n "IRC server         = $ircserver"
    fi
	
    if [[ -f "$cache" && "`grep -w "channelnr" $cache | wc -l`" = 1 ]]
    then
	echo
	channelnr=`grep -w channelnr $cache | cut -d "=" -f2 | tr -d "\""`
    else
	while [[ -z $channelnr || $channelnr -gt 15 ]]
	do
	    echo -n "How many channels do you require the bot to be in (max 15)? : " ; read channelnr
	done
    fi
	
    counta=0
	
    if [[ -f "$cache" && "`grep -w "channelnr=" $cache | wc -l`" = 0 ]]
    then
	echo channelnr=\"$channelnr\" >> $cache
    fi
	
    while [ $counta -lt $channelnr ] 
    do
	chanpassword=""
	if [[ -f "$cache" && "`grep -w "channame$((counta+1))" $cache | wc -l`" = 1 ]]
	then
	    channame=`grep -w "channame$((counta+1))" $cache | cut -d "=" -f2 | tr -d "\"" | cut -d " " -f1`
	    echo "Channel $((counta+1))          = $channame"
	else	
	    echo "Include # in the name of channel ie #main"
	    while [[ -z $channame ]] 
	    do
		echo -n "Channel $((counta+1)) is : " ; read channame
	    done
	fi
		
	if [[ -f "$cache" && "`grep -w "channame$((counta+1))" $cache | wc -l`" = 1 ]]
	then
	    chanpasswd=`grep -w "channame$((counta+1))" $cache | cut -d "=" -f2 | tr -d "\"" | cut -d " " -f2`
	    echo "Requires password  = $chanpasswd"
	else
	    echo -n "Channel password ? [Y]es [N]o, default N : " ; read chanpasswd
	fi
		
	case $chanpasswd in
	    [Yy])
                if [[ -f "$cache" && "`grep -w "announcechannels" $cache | wc -l`" = 1 ]]
                then
        	    echo "Channel mode       = password protected"
                fi
		
		if [[ -f "$cache" && "`grep -w "channame$((counta+1))" $cache | wc -l`" = 1 ]]
		then
		    chanpassword=`grep -w "channame$((counta+1))" $cache | cut -d "=" -f2 | tr -d "\"" | cut -d " " -f3`
		    echo "Channel password   = $chanpassword"
		else
		    while [[ -z $chanpassword ]]
		    do
			echo -n "Enter the channel password : " ; read chanpassword
		    done
		fi
		echo "channel set $channame chanmode {+ntpsk $chanpassword}" >> $rootdir/.tmp/bot.chan.tmp
		echo "channel add $channame {" >> $rootdir/.tmp/eggchan
		echo "idle-kick 0" >> $rootdir/.tmp/eggchan
		echo "stopnethack-mode 0" >> $rootdir/.tmp/eggchan
		echo "flood-chan 0:0" >> $rootdir/.tmp/eggchan
		echo "flood-join 0:0" >> $rootdir/.tmp/eggchan
		echo "flood-ctcp 0:0" >> $rootdir/.tmp/eggchan
		echo "flood-kick 0:0" >> $rootdir/.tmp/eggchan
		echo "flood-deop 0:0" >> $rootdir/.tmp/eggchan
		echo "flood-nick 0:0" >> $rootdir/.tmp/eggchan
		echo "aop-delay 0:0" >> $rootdir/.tmp/eggchan
		echo "chanmode \"+ntsk $chanpassword\"" >> $rootdir/.tmp/eggchan
		echo "}" >> $rootdir/.tmp/eggchan
		echo "" >> $rootdir/.tmp/eggchan
		echo $channame >> $rootdir/.tmp/channels
		
		if [[ -f "$cache" && "`grep -w "channame$((counta+1))=" $cache | wc -l`" = 0 ]]
		then
		    echo "channame$((counta+1))=\"$channame $chanpasswd $chanpassword\"" >> $cache
		fi
		;;
	    [Nn])
		if [[ -f "$cache" && "`grep -w "announcechannels" $cache | wc -l`" = 1 ]]
		then
		    echo "Channel mode       = invite only"
		fi

		echo "channel set $channame chanmode {+ntpsi}" >> $rootdir/.tmp/bot.chan.tmp
		echo "channel add $channame {" >> $rootdir/.tmp/eggchan
		echo "idle-kick 0" >> $rootdir/.tmp/eggchan
		echo "stopnethack-mode 0" >> $rootdir/.tmp/eggchan
		echo "flood-chan 0:0" >> $rootdir/.tmp/eggchan
		echo "aop-delay 0:0" >> $rootdir/.tmp/eggchan
		echo "chanmode +ntsi" >> $rootdir/.tmp/eggchan
		echo "}" >> $rootdir/.tmp/eggchan
		echo "" >> $rootdir/.tmp/eggchan
		echo $channame >> $rootdir/.tmp/channels
			
		if [[ -f "$cache" && "`grep -w "channame$((counta+1))=" $cache | wc -l`" = 0 ]]
		then
		    echo "channame$((counta+1))=\"$channame n nopass\"" $cache
		fi
		;;
	    *)
                if [[ -f "$cache" && "`grep -w "announcechannels" $cache | wc -l`" = 1 ]]
                then
                    echo "Channel mode       = invite only"
                fi
		echo "channel set $channame chanmode {+ntpsi}" >> $rootdir/.tmp/bot.chan.tmp
		echo "channel add $channame {" >> $rootdir/.tmp/eggchan
		echo "idle-kick 0" >> $rootdir/.tmp/eggchan
		echo "stopnethack-mode 0" >> $rootdir/.tmp/eggchan
		echo "flood-chan 0:0" >> $rootdir/.tmp/eggchan
		echo "aop-delay 0:0" >> $rootdir/.tmp/eggchan
		echo "chanmode +ntsi" >> $rootdir/.tmp/eggchan
		echo "}" >> $rootdir/.tmp/eggchan
		echo "" >> $rootdir/.tmp/eggchan
		echo $channame >> $rootdir/.tmp/channels
			
		if [[ -f "$cache" && "`grep -w "channame$((counta+1))=" $cache | wc -l`" = 0 ]]
		then
		    echo "channame$((counta+1))=\"$channame n nopass\"" >> $cache
		fi
		;;
	esac
	channame=""
	chanpasswd=""
	let counta=counta+1
    done

}

function announce
{
    sed -i -e :a -e N -e 's/\n/ /' -e ta $rootdir/.tmp/channels
    if [[ -f "$cache" && "`grep -w "announcechannels" $cache | wc -l`" = 1 ]]
    then
    	announcechannels=`grep -w "announcechannels" $cache | cut -d "=" -f2 | tr -d "\""`
	echo "Announce channels  = $announcechannels"
    else
	echo -n "Which should be announce channels,  default: `cat $rootdir/.tmp/channels` : " ; read announcechannels
    fi
	
    if [ "$announcechannels" = "" ] 
    then
    	announcechannels=`cat $rootdir/.tmp/channels`
	cat $rootdir/.tmp/channels > $rootdir/.tmp/dzchan

	if [[ -f "$cache" && "`grep -w "announcechannels=" $cache | wc -l`" = 0 ]]
	then
	    echo "announcechannels=\"`cat $rootdir/.tmp/channels`\"" >> $cache
	fi
		
    else 
    	echo "$announcechannels" > $rootdir/.tmp/dzchan
	
	if [[ -f "$cache" && "`grep -w "announcechannels=" $cache | wc -l`" = 0 ]]
	then
	    echo "announcechannels=\"$announcechannels\"" >> $cache
	fi
	
    fi

    if [[ -f "$cache" && "`grep -w "channelmain" $cache | wc -l`" = 1 ]]
    then
        channelmain=`grep -w "channelmain" $cache | cut -d "=" -f2 | tr -d "\""`
        echo "Main channel       = $channelmain"
    else
        echo "Channels: `cat $rootdir/.tmp/channels`"
        while [[ -z $channelmain ]]
        do
            echo -n "Which of these channels as main channel ? : " ; read channelmain
        done
    fi

    echo "$channelmain" > $rootdir/.tmp/dzmchan

    if [[ -f "$cache" && "`grep -w "channelmain=" $cache | wc -l`" = 0 ]]
    then
        echo "channelmain=\"$channelmain\"" >> $cache
    fi

    if [[ -f "$cache" && "`grep -w "channelspam" $cache | wc -l`" = 1 ]]
    then
        channelspam=`grep -w "channelspam" $cache | cut -d "=" -f2 | tr -d "\""`
        echo "Spam channel       = $channelspam"
    else
        echo "Channels: `cat $rootdir/.tmp/channels`"
        while [[ -z $channelspam ]]
        do
            echo -n "Which of these channels as spam channel ? : " ; read channelspam
        done
    fi

    echo "$channelspam" > $rootdir/.tmp/dzspamchan

    if [[ -f "$cache" && "`grep -w "channelspam=" $cache | wc -l`" = 0 ]]
    then
        echo "channelspam=\"$channelspam\"" >> $cache
    fi

    if [[ -f "$cache" && "`grep -w "channelops" $cache | wc -l`" = 1 ]]
    then
    	channelops=`grep -w "channelops" $cache | cut -d "=" -f2 | tr -d "\""`
	echo "Ops channel        = $channelops"
    else
	echo "Channels: `cat $rootdir/.tmp/channels`"
	while [[ -z $channelops ]]
	do
	    echo -n "Which of these channels as ops channel ? : " ; read channelops
	done
    fi
	
    echo "$channelops" > $rootdir/.tmp/dzochan
	
    if [[ -f "$cache" && "`grep -w "channelops=" $cache | wc -l`" = 0 ]]
    then
	echo "channelops=\"$channelops\"" >> $cache
    fi
	
    rm $rootdir/.tmp/channels
}

function ircnickname
{
    if [[ -f "$cache" && "`grep -w "ircnickname" $cache | wc -l`" = 1 ]]
    then
	ircnickname=`grep -w "ircnickname" $cache | cut -d "=" -f2 | tr -d "\""`
	echo "Nickname           = $ircnickname"
    else	
	while [[ -z $ircnickname ]] 
	do
	    echo -n "What is your nickname on irc ? ie l337 : " ; read ircnickname
	done
    fi
	
    if [[ -f "$cache" && "`grep -w "ircnickname=" $cache | wc -l`" = 0 ]]
    then
	echo "ircnickname=\"$ircnickname\"" >> $cache
    fi
}

## how many sections
function glftpd
{
    if [[ -f "$cache" && "`grep -w "eur0presystem" $cache | wc -l`" = 1 ]]
    then
	echo "Sections           = `cat $rootdir/.tmp/.validsections`"
    fi
    if [[ -f "$cache" && "`grep -w "router" $cache | wc -l`" = 1 ]]
    then
        echo "Router             = "`grep -w "router" $cache | cut -d "=" -f2 | tr -d "\""`
    fi
    if [[ -f "$cache" && "`grep -w "pasv_addr" $cache | wc -l`" = 1 ]]
    then
	echo "Passive address    = "`grep -w "pasv_addr" $cache | cut -d "=" -f2 | tr -d "\""`
    fi
    if [[ -f "$cache" && "`grep -w "pasv_ports" $cache | wc -l`" = 1 ]]
    then
        echo "Port range         = "`grep -w "pasv_ports" $cache | cut -d "=" -f2 | tr -d "\""`
    fi
    if [[ -f "$cache" && "`grep -w "psxcimdbchan" $cache | wc -l`" = 1 ]]
    then
        echo "IMDB channels      = "`grep -w "psxcimdbchan" $cache | cut -d "=" -f2 | tr -d "\""`
    fi

    echo
    echo "--------[ Installation of software and scripts ]----------------------"
    packages/scripts/tur-rules/rulesgen.sh MISC
    cd packages
    echo
    echo -n "Installing glftpd, please wait..." | awk '{printf("%-64s",$0)}'
    echo "####### Here starts glFTPd scripts #######" >> /var/spool/cron/crontabs/root
    cd $PK1DIR && sed "s/changeme/$port/" ../core/installgl.sh.org > installgl.sh && chmod +x installgl.sh && ./installgl.sh >/dev/null 2>&1
    >$glroot/ftp-data/misc/welcome.msg
    echo -e "[\e[32mDone\e[0m]"
    cd ../core
    echo "##########################################################################" > glftpd.conf
    echo "# Server shutdown: 0=server open, 1=deny all but siteops, !*=deny all, etc" >> glftpd.conf
    echo "shutdown 1" >> glftpd.conf
    echo "#" >> glftpd.conf
    echo "sitename_long		$sitename" >> glftpd.conf
    echo "sitename_short		$sitename" >> glftpd.conf
    echo "email			root@localhost.org" >> glftpd.conf
    echo "login_prompt 		$sitename[:space:]Ready" >> glftpd.conf
    echo "mmap_amount     	100"  >> glftpd.conf
    echo "# SECTION		KEYWORD		DIRECTORY	SEPARATE CREDITS" >> glftpd.conf
    echo "stat_section		DEFAULT 	* 		no" >> glftpd.conf
    if [[ -f "$cache" && "`grep -w "router" $cache | wc -l`" = 1 ]]
    then
	router=`grep -w "router" $cache | cut -d "=" -f2 | tr -d "\""`
    else
	echo -n "Do you use a router ? [Y]es [N]o, default N : " ; read router
    fi
    case $router in
	[Yy])
	    wgetbinary=`which wget`
	    ipcheck="`$wgetbinary -qO- http://ipecho.net/plain ; echo`"
	    if [[ -f "$cache" && "`grep -w "pasv_addr" $cache | wc -l`" = 1 ]]
	    then
		pasv_addr=`grep -w "pasv_addr" $cache | cut -d "=" -f2 | tr -d "\""`
	    else	
		echo -n "Please enter the DNS or IP for the site, default $ipcheck : " ; read pasv_addr
	    fi
			
	    if [ "$pasv_addr" = "" ] 
	    then
		pasv_addr="$ipcheck"
	    fi
		
	    if [[ -f "$cache" && "`grep -w "pasv_ports" $cache | wc -l`" = 1 ]]
	    then
		pasv_ports=`grep -w "pasv_ports" $cache | cut -d "=" -f2 | tr -d "\""`
	    else
		echo -n "Please enter the port range for passive mode, default 6000-7000 : " ; read pasv_ports
	    fi
		
	    echo "pasv_addr		$pasv_addr	1" >> glftpd.conf
	    if [ "$pasv_ports" = "" ] 
	    then
	    	echo "pasv_ports		6000-7000" >> glftpd.conf
	    	pasv_ports="6000-7000"
	    else
		echo "pasv_ports		$pasv_ports" >> glftpd.conf
	    fi
	    ;;
	[Nn]) router=n ;;
	*) router=n ;;
    esac
	
    if [[ -f "$cache" && "`grep -w "router=" $cache | wc -l`" = 0 ]]
    then
	echo "router=\"$router\"" >> $cache
    fi
	
    if [[ -f "$cache" && "`grep -w "pasv_addr=" $cache | wc -l`" = 0 && "$pasv_addr" != "" ]]
    then
    	echo "pasv_addr=\"$pasv_addr\"" >> $cache
    fi
	
    if [[ -f "$cache" && "`grep -w "pasv_ports=" $cache | wc -l`" = 0 && "$pasv_addr" != "" ]]
    then
    	echo "pasv_ports=\"$pasv_ports\"" >> $cache
    fi
	
    #cat glstat >> glftpd.conf && rm glstat
    cat glfoot >> glftpd.conf && mv glftpd.conf $glroot/etc
    cp -f default.user $glroot/ftp-data/users
    echo "59 23 * * * 		`which chroot` $glroot /bin/cleanup >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    echo "29 4 * * * 		`which chroot` $glroot /bin/datacleaner >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    echo "*/10 * * * * 		$glroot/bin/incomplete-list-nuker.sh >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    touch $glroot/ftp-data/logs/incomplete-list-nuker.log
    echo "0 1 * * *       	$glroot/bin/olddirclean2 -PD >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    mv ../scripts/tur-space/tur-space.conf.new $glroot/bin/tur-space.conf
    cp ../scripts/tur-space/tur-space.sh $glroot/bin
    cp ../scripts/tur-precheck/tur-precheck.sh $glroot/bin
    cp ../scripts/tur-predircheck/tur-predircheck.sh $glroot/bin
    cp ../scripts/tur-predircheck_manager/tur-predircheck_manager.sh $glroot/bin
    cp ../scripts/tur-free/tur-free.sh $glroot/bin
    sed -i '/^SECTIONS/a '"TOTAL:$device" $glroot/bin/tur-free.sh
    sed -i "s/changeme/$sitename/" $glroot/bin/tur-free.sh
    gcc ../scripts/tur-predircheck/glftpd2/dirloglist_gl.c -o $glroot/bin/dirloglist_gl
    gcc -O2 ../extra/tur-ftpwho/tur-ftpwho.c -o $glroot/bin/tur-ftpwho
    gcc ../extra/tuls/tuls.c -o $glroot/bin/tuls
    rm -f $glroot/README
    rm -f $glroot/README.ALPHA
    rm -f $glroot/UPGRADING
    rm -f $glroot/changelog
    rm -f $glroot/LICENSE
    rm -f $glroot/LICENCE
    rm -f $glroot/glftpd.conf
    rm -f $glroot/installgl.debug
    rm -f $glroot/installgl.sh
    rm -f $glroot/glftpd.conf.dist
    rm -f $glroot/convert_to_2.0.pl
    rm -f /etc/glftpd.conf
    mv -f $glroot/create_server_key.sh $glroot/etc
    mv -f ../../site.rules $glroot/ftp-data/misc
    cp ../extra/incomplete-list.sh $glroot/bin
    cp ../extra/incomplete-list-nuker.sh $glroot/bin
    cp ../extra/incomplete-list-symlinks.sh $glroot/bin
    cp ../extra/lastlogin.sh $glroot/bin
    chmod 755 $glroot/site
    ln -s $glroot/etc/glftpd.conf /etc/glftpd.conf
    chmod 777 $glroot/ftp-data/msgs
    cp ../extra/update_perms.sh $glroot/bin
    cp ../extra/update_gl.sh $glroot/bin
    cp ../extra/imdb-scan.sh $glroot/bin
    cp ../extra/imdb-rescan.sh $glroot/bin
    cp ../extra/glftpd-version-check.sh $glroot/bin
    echo "0 18 * * *              $glroot/bin/glftpd-version-check.sh >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    cp ../scripts/section-manager/section-manager.sh $glroot
    sed -i "s|changeme|$device|" $glroot/section-manager.sh
    cp ../scripts/imdbrating/imdbrating.sh $glroot/bin
    sed -i s/10.10s/10.20s/ $glroot/ftp-data/text/ginfo.body
    bins="bc du expr echo sed touch chmod chown pwd grep basename date mv bash find sort which xargs"
    for file in $bins
    do
        cp `which $file` $glroot/bin
    done
    if [ -f /etc/systemd/system/glftpd.socket ]
    then
        sed -i 's/#MaxConnections=64/MaxConnections=300/' /etc/systemd/system/glftpd.socket
        systemctl daemon-reload && systemctl restart glftpd.socket
    fi
}

## EGGDROP
function eggdrop
{
    if [[ -f "$cache" && "`grep -w "eur0presystem" $cache | wc -l`" = 0 ]]
    then
    	echo
    fi
    echo -n "Installing eggdrop, please wait..." | awk '{printf("%-64s",$0)}'
    cd ../$PK3DIR ; ./configure --prefix="$glroot/sitebot" >/dev/null 2>&1 && make config >/dev/null 2>&1  && make >/dev/null 2>&1 && make install >/dev/null 2>&1
    cd ../core
    cat egghead > eggdrop.conf
    cat $rootdir/.tmp/eggchan >> eggdrop.conf
    cat bot.chan | sed "s/changeme/$sitename/" > $glroot/sitebot/logs/bot.chan
    cat $rootdir/.tmp/bot.chan.tmp >> $glroot/sitebot/logs/bot.chan
    echo "set username 		\"$sitename\"" >> eggdrop.conf
    echo "set nick 		\"$sitename\"" >> eggdrop.conf
    echo "set altnick 		\"_$sitename\"" >> eggdrop.conf
    cat eggfoot >> eggdrop.conf
    sed -i "s/changeme/$ircnickname/" eggdrop.conf
    mv eggdrop.conf $glroot/sitebot
    cp botchkhead .botchkhead
    echo "botdir=$glroot/sitebot" >> .botchkhead
    echo "botscript=sitebot" >> .botchkhead
    echo "botname=$sitename" >> .botchkhead
    echo "userfile=./logs/bot.user" >> .botchkhead
    echo "pidfile=pid.$sitename" >> .botchkhead
    chmod 755 .botchkhead
    mv .botchkhead $glroot/sitebot/botchk
    cat botchkfoot >> $glroot/sitebot/botchk
    touch /var/spool/cron/crontabs/$BOTU
    echo "*/10 * * * *	$glroot/sitebot/botchk >/dev/null 2>&1" >> /var/spool/cron/crontabs/$BOTU
    chmod 777 $glroot/sitebot/logs
    rm -f $glroot/sitebot/BOT.INSTALL
    rm -f $glroot/sitebot/README
    rm -f $glroot/sitebot/eggdrop1.8
    rm -f $glroot/sitebot$glroot-tcl.old-TIMER
    rm -f $glroot/sitebot$glroot.tcl-TIMER
    rm -f $glroot/sitebot/eggdrop
    rm -f $glroot/sitebot/eggdrop-basic.conf
    rm -f $glroot/sitebot/scripts/CONTENTS
    rm -f $glroot/sitebot/scripts/autobotchk
    rm -f $glroot/sitebot/scripts/botchk
    rm -f $glroot/sitebot/scripts/weed
    ln -s $glroot/sitebot/`ls $glroot/sitebot | grep eggdrop-` $glroot/sitebot/sitebot
    chmod 666 $glroot/etc$glroot.conf
    mkdir -pm 777 $glroot/site/PRE/SiteOP $glroot/site/SPEEDTEST
    chmod 777 $glroot/site/PRE
    dd if=/dev/urandom of=$glroot/site/SPEEDTEST/150MB bs=1M count=150 >/dev/null 2>&1
    dd if=/dev/urandom of=$glroot/site/SPEEDTEST/250MB bs=1M count=250 >/dev/null 2>&1
    dd if=/dev/urandom of=$glroot/site/SPEEDTEST/500MB bs=1M count=500 >/dev/null 2>&1
    rm -f $glroot/sitebot/scripts/*.tcl
    cp ../extra/*.tcl $glroot/sitebot/scripts
    sed -i "s/#changeme/$announcechannels/" $glroot/sitebot/scripts/rud-news.tcl
    sed -i "s/#personal/$channelops/" $glroot/sitebot/scripts/rud-news.tcl
    mv -f ../scripts/tur-rules/tur-rules.sh $glroot/bin
    cp ../scripts/tur-rules/*.tcl $glroot/sitebot/scripts
    cp ../scripts/tur-free/*.tcl $glroot/sitebot/scripts
    cp ../scripts/tur-predircheck_manager/tur-predircheck_manager.tcl $glroot/sitebot/scripts
    sed -i "s/changeme/$channelops/g" $glroot/sitebot/scripts/tur-predircheck_manager.tcl
    cp ../extra/kill.sh $glroot/sitebot
    sed -i "s/changeme/$sitename/g" $glroot/sitebot/kill.sh
    echo "source scripts/tur-free.tcl" >> $glroot/sitebot/eggdrop.conf
    echo -e "[\e[32mDone\e[0m]"
}

function irc
{
    if [[ -f "$cache" && "`grep -w "ircserver" $cache | wc -l`" = 1 ]]
    then
	sed -i "s/servername/$ircserver/" $glroot/sitebot/eggdrop.conf
    else
	echo
    	echo -n "What irc server ? default irc.example.org : " ; read servername

	if [ "$servername" = "" ] 
	then
	    servername="irc.example.org"
	fi
		
	echo -n "What port for irc server ? default 7000 : " ; read serverport
	if [ "$serverport" = "" ] 
	then
	    serverport="7000"
	fi
		
	echo -n "Is the port above a SSL port ? [Y]es [N]o, default Y : " ; read serverssl
	case $serverssl in
	    [Yy]) ssl=1	;;
	    [Nn]) ssl=0	;;
	    *) ssl=1 ;;
	esac
		
	echo -n "Does it require a password ? [Y]es [N]o, default N : " ; read serverpassword
	case $serverpassword in
	    [Yy])
		echo -n "Please enter the password for irc server, default ircpassword : " ; read password
		if [ "$password" = "" ] 
		then
		    password=":ircpassword"
		else
		    password=":$password"
		fi
		;;
	    [Nn]) password="" ;;
	    *) password="" ;;
	esac
		
	case $ssl in
	    1)
		sed -i "s/servername/${servername} +${serverport} ${password}/" $glroot/sitebot/eggdrop.conf
		
		if [[ -f "$cache" && "`grep -w "ircserver=" $cache | wc -l`" = 0 ]]
		then
		    echo "ircserver=\"${servername} +${serverport} ${password}\"" >> $cache
		fi
		;;
	    0)
		sed -i "s/servername/${servername} ${serverport} ${password}/" $glroot/sitebot/eggdrop.conf
		
		if [[ -f "$cache" && "`grep -w "ircserver=" $cache | wc -l`" = 0 ]]
		then
		    echo "ircserver=\"${servername} ${serverport} ${password}\"" >> $cache
		fi
		;;
	esac
    fi
}

## zsconfig.h
function pzshfile
{
    cd ../../
    cat packages/core/pzshead > zsconfig.h
    echo "/site/REQUESTS/" >> $rootdir/.tmp/.nodatepath
    [ -f "$rootdir/.tmp/.path" ] && paths="`cat $rootdir/.tmp/.path`"
    [ -f "$rootdir/.tmp/.cleanup_dated" ] && cleanup_dated=`cat $rootdir/.tmp/.cleanup_dated | sed 's/ /\n/g' | sort | xargs`
    nodatepaths="`cat $rootdir/.tmp/.nodatepath`"
    allsections=`echo "$paths $nodatepaths" | sed 's/ /\n/g' | sort | xargs | sed 's/^ //'`
    echo "#define check_for_missing_nfo_dirs		\"$allsections\"" >> zsconfig.h
    echo "#define cleanupdirs				\"$nodatepaths\"" >> zsconfig.h
    echo "#define cleanupdirs_dated			\"$cleanup_dated\"" >> zsconfig.h
    echo "#define sfv_dirs				\"$allsections\"" >> zsconfig.h
    echo "#define short_sitename				\"$sitename\"" >> zsconfig.h
    chmod 755 zsconfig.h
    mv zsconfig.h packages/pzs-ng/zipscript/conf/zsconfig.h
}

## dZSbot.tcl
function pzsbotfile
{
    cat packages/core/dzshead > ngBot.conf
    echo "set device(0)"				'"'$device SITE'"' >> ngBot.conf
    cat packages/core/dzsbnc >> ngBot.conf
    echo "REQUEST" >> $rootdir/.tmp/.validsections
    echo "set paths(REQUEST)			\"/site/REQUESTS/*/*\"" >> $rootdir/.tmp/dzsrace
    echo "set chanlist(REQUEST)			\"$announcechannels\"" >> $rootdir/.tmp/dzschan
    cat packages/core/dzsmidl  >> ngBot.conf
    echo "set sections				\"`cat $rootdir/.tmp/.validsections`\"" >> ngBot.conf
    echo "" >> ngBot.conf
    #cat $rootdir/.tmp/dzsstats >> ngBot.conf
    cat $rootdir/.tmp/dzsrace >> ngBot.conf && rm $rootdir/.tmp/dzsrace
    cat $rootdir/.tmp/dzschan >> ngBot.conf && rm $rootdir/.tmp/dzschan
    cat packages/core/dzsfoot >> ngBot.conf
    chmod 644 ngBot.conf
    mkdir -p $glroot/sitebot/scripts/pzs-ng/themes
    mv ngBot.conf $glroot/sitebot/scripts/pzs-ng/ngBot.conf
}

## PROJECTZS
function pzsng
{
    if [[ -f "$cache" && "`grep -w "eur0presystem" $cache | wc -l`" = 0 ]]
    then
    	echo
    fi
    echo -n "Installing pzs-ng, please wait..." | awk '{printf("%-64s",$0)}'
    cd packages/pzs-ng
    ./configure >/dev/null 2>&1 ; make >/dev/null 2>&1 ; make install >/dev/null 2>&1
    $glroot/libcopy.sh >/dev/null 2>&1
    echo -e "[\e[32mDone\e[0m]"
    cp sitebot/ngB* $glroot/sitebot/scripts/pzs-ng/
    mkdir $glroot/sitebot/scripts/pzs-ng/modules
    cp sitebot/modules/glftpd.tcl $glroot/sitebot/scripts/pzs-ng/modules
    mkdir $glroot/sitebot/scripts/pzs-ng/plugins
    cp ../core/glftpd-installer.theme $glroot/sitebot/scripts/pzs-ng/themes
    cp ../core/ngBot.vars $glroot/sitebot/scripts/pzs-ng
    cp -f ../core/sitewho.conf $glroot/bin
    rm -f $glroot/sitebot/scripts/pzs-ng/ngBot.conf.dist
}

function modules
{
    cd $rootdir
    for module in `ls ./packages/modules`
    do
	. packages/modules/$module/$module.inc
    done
}

## usercreation
function usercreation
{
    if [[ -f "$cache" && "`grep -w "username" $cache | wc -l`" = 1 ]]
    then
	username=`grep -w "username" $cache | cut -d "=" -f2 | tr -d "\""`
    else
	echo
	echo "--------[ FTP user configuration ]------------------------------------"
	echo
	echo -n "Please enter the username of admin, default admin : " ; read username
    fi
	
    if [ "$username" = "" ] 
    then
    	username="admin"
    fi

    if [[ -f "$cache" && "`grep -w "password" $cache | wc -l`" = 1 ]]
    then
    	password=`grep -w "password" $cache | cut -d "=" -f2 | tr -d "\""`
    else
    	echo -n "Please enter the password [$username], default password : " ; read password
    fi
	
    if [ "$password" = "" ] 
    then
    	password="password"
    fi

    localip=`ip addr show | awk '$1 == "inet" && $3 == "brd" { sub (/\/.*/,""); print $2 }' | head | awk -F "." '{print $1"."$2"."$3.".*"}'`
    netip=`wget -qO- http://ipecho.net/plain | awk -F "." '{print $1"."$2"."$3.".*"}'`
	
    if [[ -f "$cache" && "`grep -w "ip" $cache | wc -l`" = 1 ]]
    then
	ip=`grep -w "ip" $cache | cut -d "=" -f2 | tr -d "\""`
    else
	echo -n "IP for [$username] ? Type without *@ or ident@. Minimum xxx.xxx.* default $localip $netip : " ; read ip
    fi
	
    if [ "$ip" = "" ] 
    then
	if [ "$localip" = "$netip" ]
	then
	    ip="*@$netip"
	else
	    ip="*@$localip *@$netip"
	fi
    fi

    if [[ -f "$cache" && "`grep -w "username=" $cache | wc -l`" = 0 ]]
    then
	echo "username=\"$username\"" >> $cache
	echo "password=\"$password\"" >> $cache
	echo "ip=\"*@$ip\"" >> $cache
    fi

    if [ "$router" = "y" ] 
    then
	connection="-E ftp://localhost"
    else
	connection="ftp://localhost"
    fi

    success="230 User glftpd logged in."
status=`ftp -nv localhost $port <<EOF
quote USER glftpd
quote PASS glftpd
quit
EOF`
    if [ "`echo $status | grep -c "$success"`" -eq 0 ]
    then
	if [ -e /etc/systemd/system/glftpd.socket ]
	then
	    systemctl stop glftpd.socket >/dev/null && systemctl start glftpd.socket >/dev/null
	fi
	if [ -e /etc/rc.d/rc.inetd ]
	then
	    /etc/rc.d/rc.inetd stop >/dev/null && /etc/rc.d/rc.inetd start >/dev/null
	fi
    fi
    if [ "`echo $status | grep -c "$success"`" -eq 1 ]
    then
	ncftpls -u glftpd -p glftpd -P $port -Y "site change glftpd flags +347ABCDEFGH" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd SiteOP SiteOP" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd Admin Administrators/SYSOP" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd Friends Friends" $connection > /dev/null
    	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd NUKERS NUKERS" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd VACATION VACATION" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site grpadd iND Independent Racers" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site gadduser Admin $username $password $ip" $connection > /dev/null
    	ncftpls -u glftpd -p glftpd -P $port -Y "site chgrp $username SiteOP" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site change $username flags +1347ABCDEFGH" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site change $username ratio 0" $connection > /dev/null
	ncftpls -u glftpd -p glftpd -P $port -Y "site chgrp glftpd glftpd" $connection > /dev/null
	echo
	echo "[$username] created successfully and added to the groups Admin and SiteOP"
	echo "These groups were also created: NUKERS, iND, VACATION & Friends"
    else
    	echo -e "\e[0;31mCouldn't connect to the newly installed FTP and add user and groups. Manual add of user and groups is needed.\e[0m"
    fi
    sed -i "s/\"changeme\"/\"$username\"/" $glroot/sitebot/eggdrop.conf
    sed -i "s/\"sname\"/\"$sitename\"/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
    sed -i "s/\"ochan\"/\"$channelops\"/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
    sed -i "s/(ochan)/($channelops)/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
    sed -i "s/\"mainname\"/\"$channelmain\"/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
    sed -i "s/\"spamname\"/\"$channelspam\"/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
    sed -i "s/\"invitename\"/\"$announcechannels\"/" $glroot/sitebot/scripts/pzs-ng/ngBot.conf
}

## CleanUp / Config
function cleanup
{
    cd $rootdir
    if [ ! -d $glroot/backup ]; then mkdir $glroot/backup ; fi
    mv packages/$PK1DIR packages/source/
    mv packages/$PK2DIR packages/source/
    mv packages/$PK3DIR packages/source/
    if [ "$(cat install.cache | grep eur0presystem | cut -d "=" -f2 | tr -d "\"")" = "y" ]; then mv packages/modules/eur0-pre-system/foo-tools packages/source/ ; fi
    mv $rootdir/.tmp/site/* $glroot/site/
    cp -r packages/source/pzs-ng $glroot/backup
    cp packages/extra/pzs-ng-update.sh $glroot/backup 
    cp packages/extra/backup.sh $glroot/backup && sed -i "s/changeme/$sitename/" $glroot/backup/backup.sh
    sed -i "s/pass=/pass=$SQLPASSWD/" $glroot/backup/backup.sh
    cp $glroot/backup/pzs-ng/sitebot/extra/invite.sh $glroot/bin
    cp packages/extra/syscheck.sh $glroot/bin
    mv -f $rootdir/.tmp/dated.sh $glroot/bin
    
    for sec in `grep section.*dated=\"y\" $cache | sed -e 's/section//' -e 's/dated//' | cut -d '=' -f1`
    do
	dated=`grep "section$sec=" $cache | cut -d '=' -f2 | tr -d '"'`
	sed -i '/^sections/a '"$dated" $glroot/bin/dated.sh
    done
	
    if [ `grep 'section.*dated="y"' $cache | wc -l` -ge 1 ]
    then
        echo "0 0 * * *         	$glroot/bin/dated.sh >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
        $glroot/bin/dated.sh >/dev/null 2>&1
    fi

    if [ "`ls $glroot/site | grep "^TV*" | wc -l`" -ge 1 ]
    then
        cp -f packages/scripts/tvmaze/TVMaze.tcl $glroot/sitebot/scripts/pzs-ng/plugins
        cp -f packages/scripts/tvmaze/TVMaze.zpt $glroot/sitebot/scripts/pzs-ng/plugins
        cp packages/scripts/tvmaze/*.sh $glroot/bin
        echo "source scripts/pzs-ng/plugins/TVMaze.tcl" >> $glroot/sitebot/eggdrop.conf
	for tv in `ls $glroot/site | grep "^TV*"`
	do
	    sed -i "s|set tvmaze(sections) {|set tvmaze(sections) { \"/site/$tv/\" |" $glroot/sitebot/scripts/pzs-ng/plugins/TVMaze.tcl
	done 
	$glroot/bin/tvmaze-nuker.sh sanity >/dev/null 2>&1
    fi

    echo "#*/5 * * * *		$glroot/bin/tur-space.sh go >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
    touch $glroot/ftp-data/logs/tur-space.log
    mkdir -m 777 $glroot/tmp
    chown -R $BOTU:glftpd $glroot/sitebot
    $glroot/bin/update_perms.sh
    chmod 777 $glroot/ftp-data/logs
    chmod 666 $glroot/ftp-data/logs/*
    echo "EOF" >> $glroot/sitebot/eggdrop.conf && cat $glroot/sitebot/eggdrop.conf | sed -n '/MY SCRIPTS/,/EOF/p' | sort > .tmp/myscripts && sed -i '/EOF/d' .tmp/myscripts
    sed -i '/MY SCRIPTS/,$d' $glroot/sitebot/eggdrop.conf
    cat .tmp/myscripts >> $glroot/sitebot/eggdrop.conf
    rm -rf .tmp >/dev/null 2>&1
    rm -rf $glroot/glftpd-LNX_current
    rm -f packages/modules/tur-autonuke/tur-autonuke.conf
    [ -d /etc/rsyslog.d ] && cp packages/extra/glftpd.conf /etc/rsyslog.d && service rsyslog restart
    cp packages/extra/rescan_fix.sh $glroot/bin
    echo "*/2 * * * *             $glroot/bin/rescan_fix.sh >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
}
version
start
port
device_name
channel
announce
ircnickname
create_section_workflow
glftpd
eggdrop
irc
pzshfile
pzsbotfile
pzsng
modules
usercreation
cleanup
echo 
echo "If you are planning to uninstall glFTPd then run cleanup.sh"
echo
echo "To get the bot running you HAVE to do this ONCE to create the initial userfile"
echo "su - sitebot -c \"$glroot/sitebot/sitebot -m\""
echo
echo "If you want automatic cleanup of site then please review the settings in $glroot/bin/tur-space.conf and enable the line in crontab"
echo 
echo "All good to go and I recommend people to check the different settings for the different scripts including glFTPd itself."
echo
echo "Enjoy!"
echo 
echo "Installer script created by Teqno" 

exit 0
